
CREATE TABLE USER(
	ID INTEGER AUTO_INCREMENT,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
    EMAIL VARCHAR(60),
    PASSWORD VARCHAR(20),
    PRIMARY KEY (ID, EMAIL),
    UNIQUE KEY users_email_unique (EMAIL)
)ENGINE=INNODB;

INSERT INTO USER VALUES(NULL, "Mark", "Clinton", "mark@gmail.com", "12345");
INSERT INTO USER VALUES(NULL, "john", "doe", "john@gmail.com", "12345");

CREATE TABLE TASKS (
	TASK_ID INTEGER AUTO_INCREMENT,
	TASK_NAME VARCHAR(30),
	USER_ID INTEGER,
	TASK_INFO TEXT,
	TASK_DATE DATE,
	START_TIME TIME,
	END_TIME TIME,
	PRIMARY KEY(TASK_ID),
	FOREIGN KEY fk_task (USER_ID) REFERENCES USER (ID)
) ENGINE=INNODB;

INSERT INTO TASKS VALUES (NULL, "Meeting", 1, "Meeting with lawyer", "30-01-2017", "15:00", "16:00");
INSERT INTO TASKS VALUES (NULL, "Meeting", 1, "Meeting with lawyer", "30-01-2017", "15:00", "16:00");
INSERT INTO TASKS VALUES (NULL, "Meeting", 1, "Meeting with lawyer", "30-01-2017", "15:00", "16:00");
INSERT INTO TASKS VALUES (NULL, "Meeting", 1, "Meeting with lawyer", "30-01-2017", "15:00", "16:00");
INSERT INTO TASKS VALUES (NULL, "Meeting", 2, "Meeting with lawyer", "30-01-2017", "15:00", "16:00");


CREATE TABLE SHARE (
	USER_ID INTEGER,
	TASK_ID INTEGER,
	PRIMARY KEY (USER_ID, TASK_ID),
	FOREIGN KEY fk_task_id (TASK_ID) REFERENCES TASKS (TASK_ID),
	FOREIGN KEY fk_contributor (USER_ID) REFERENCES USER (ID) 
)ENGINE=INNODB;


INSERT INTO SHARE VALUES (1, 1);
INSERT INTO SHARE VALUES (2, 1);


CREATE TABLE FRIENDS (
	USER_ID INTEGER,
	FRIEND_ID INTEGER,
	PRIMARY KEY (USER_ID, FRIEND_ID),
	FOREIGN KEY fk_user_id (USER_ID) REFERENCES USER (ID),
	FOREIGN KEY fk_friend_id (FRIEND_ID) REFERENCES USER (ID)
)ENGINE=INNODB;

INSERT INTO FRIENDS VALUES (1,2);
INSERT INTO FRIENDS VALUES (2,1);

